### ISSUE TITLE
AssertionError: extension access disabled because of command line flags

### ISSUE THREAD

**Issue by zanganoabeja** [bigchirv/docker_sd_webui_gfx1100#3]
I'm having problems installing the sd-webui-controlnet extension, it gives me an error and refuses to install it.

```
Error completing request
Arguments: ('https://github.com/Mikubill/sd-webui-controlnet.git', ['ads', 'localization', 'installed'], 0, 'sd-webui-controlnet') {}
Traceback (most recent call last):
  File "/srv/webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/srv/webui/modules/ui_extensions.py", line 178, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/srv/webui/modules/ui_extensions.py", line 133, in install_extension_from_url
    check_access()
  File "/srv/webui/modules/ui_extensions.py", line 21, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags

```

**Comment by chirvo** [comment]
Have you tried with the develop branch? The only parameters I pass to a1111 is --listen, to make its web ui listen on the tcp port

**Comment by zanganoabeja** [comment]
I haven't tried the develop branch, but I did manage to install the extensions by using another webui, donwloading the extensions there and then passing them over.

**Comment by chirvo** [comment]
Good you managed to solve your issue. Thanks for documenting your workaround. Cheers.
